#goal definition
nav_2d_msgs/Pose2DStamped start 
nav_2d_msgs/Pose2DStamped goal 
---
#result definition
nav_2d_msgs/Path2D path
builtin_interfaces/Duration planning_time
---
#feedback
builtin_interfaces/Duration elapsed_time
